name: Feature request
description: Suggest an idea for chargecap.
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: Describe the problem you want to solve.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you want.
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe any alternative solutions you considered.
    validations:
      required: false
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I checked existing issues
          required: true
